// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  cas.RodVisualiser2 = (function(_super) {
    __extends(RodVisualiser2, _super);

    RodVisualiser2.prototype.NAME = "RodModel2";

    RodVisualiser2.prototype.INFO = "The RodModel2 visualiser calculates the desired length of a whole pull, minus handstroke gap, by averaging the difference between the midpoint of the bells striking in the next whole pull and that of the previous whole pull. Handstroke gap is the average gap for the ringing so far.";

    RodVisualiser2.prototype.fLastRow = null;

    RodVisualiser2.prototype.fTotalHandstrokeGap = 0.0;

    RodVisualiser2.prototype.fTotalInterbellGap = 0.0;

    RodVisualiser2.prototype.fCurrentHandstrokeGap = 0.0;

    function RodVisualiser2() {
      RodVisualiser2.__super__.constructor.call(this, this.NAME, this.INFO);
    }

    RodVisualiser2.prototype.clearData = function() {
      var fCurrentHandstrokeGap, fLastRow, fTotalHandstrokeGap, fTotalInterbellGap;
      RodVisualiser2.__super__.clearData.apply(this, arguments);
      fLastRow = null;
      fTotalHandstrokeGap = 0.0;
      fTotalInterbellGap = 0.0;
      return fCurrentHandstrokeGap = 0.0;
    };

    RodVisualiser2.prototype.getCurrentHandstrokeGap = function() {
      return this.fCurrentHandstrokeGap;
    };

    RodVisualiser2.prototype.newRow = function(row) {
      if (row.getRowSize() > 1) {
        this.fTotalInterbellGap += (row.getBong(row.getRowSize()).time - row.getBong(1).time) / (row.getRowSize() - 1);
      }
      if (row.isHandstroke() && (this.fLastRow != null)) {
        this.fTotalHandstrokeGap += row.getStrikeTime(1) - this.fLastRow.getStrikeTime(this.fLastRow.getRowSize());
        this.fCurrentHandstrokeGap = this.fTotalHandstrokeGap / this.fTotalInterbellGap;
      }
      this.fLastRow = row;
      return RodVisualiser2.__super__.newRow.apply(this, arguments);
    };

    return RodVisualiser2;

  })(cas.RodBaseVisualiser);

}).call(this);
