// Generated by CoffeeScript 1.7.1
(function() {
  cas.SensorEchoCorrecter = (function() {
    SensorEchoCorrecter.prototype.fBongs = new Array(cas.MAXNBELLS);

    function SensorEchoCorrecter(quickestStrikeTime) {
      if (quickestStrikeTime == null) {
        quickestStrikeTime = cas.QUICKEST_STRIKE_TIME;
      }
      this.fQuickestStrikeTime = quickestStrikeTime;
    }

    SensorEchoCorrecter.prototype.receiveBong = function(bong) {
      var prevBong;
      prevBong = this.fBongs[bong.bell - 1];
      if ((prevBong == null) || bong.time - prevBong.time >= this.fQuickestStrikeTime) {
        this.fBongs[bong.bell - 1] = bong;
        return this.fNextStage.receiveBong(bong);
      }
    };

    SensorEchoCorrecter.prototype.notifyInputComplete = function() {
      return this.fNextStage.notifyInputComplete();
    };

    SensorEchoCorrecter.prototype.setNextStage = function(nextStage) {
      return this.fNextStage = nextStage;
    };

    return SensorEchoCorrecter;

  })();

}).call(this);
