// Generated by CoffeeScript 1.7.1
(function() {
  cas.StrokeCorrecter = (function() {
    StrokeCorrecter.prototype.fBongs = new Array(cas.MAXNBELLS);

    function StrokeCorrecter(handstrokeStart) {
      if (handstrokeStart == null) {
        handstrokeStart = true;
      }
      this.fHandstrokeStart = handstrokeStart;
      this.fStroke = this.fHandstrokeStart ? cas.HANDSTROKE : cas.BACKSTROKE;
    }

    StrokeCorrecter.prototype.receiveBong = function(bong) {
      var i, prevBong, _i, _ref;
      prevBong = this.fBongs[bong.bell - 1];
      if (prevBong != null) {
        this.fStroke = -this.fStroke;
        for (i = _i = 0, _ref = this.fBongs.length; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
          this.fBongs[i] = null;
        }
      }
      this.fBongs[bong.bell - 1] = bong;
      bong.stroke = this.fStroke;
      return this.fNextStage.receiveBong(bong);
    };

    StrokeCorrecter.prototype.notifyInputComplete = function() {
      return this.fNextStage.notifyInputComplete();
    };

    StrokeCorrecter.prototype.setNextStage = function(nextStage) {
      return this.fNextStage = nextStage;
    };

    return StrokeCorrecter;

  })();

}).call(this);
